- hosts: all
  gather_facts: no
  become: no
  tasks:
  - name: Enable Heketi node
    command: "heketi-cli
                 --server={{ heketi_server }}
                 --user={{ heketi_user }}
                 --secret={{ heketi_secret }}
                 node enable {{ heketi_node_id }}"
